version: "3.9"

services:
  redis-container:
    image: redis:7
    command: /opt/sh/start-redis.sh
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis-data:/var/lib/redis
      - ./scripts/sh/:/opt/sh/
volumes:
  redis-data:
    name: redis-data
    external: false