version: "3.9"

services:
  redis-container:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
volumes:
  redis-data:
    name: redis-data
    external: false