spring:
  application:
    name: ratelimit-service

redis:
  redisHost: redis://127.0.0.1
  redisPort: 6379
  redisPassword: password
  redisConnectionTimeout: 2000
  redisPoolMaxIdle: 50
  redisPoolMinIdle: 10
  redisPoolMaxWaitMillis: -1
  redisPoolMaxTotal: 200
  redisKeyPrefix: #RL
  checkActionTimeout: 100

intuit:
  ratelimit:
    algorithm: SLIDING
    enabled: true
    repository: REDIS
    service:
      serviceA:
          limit: 10
          refreshInterval: 60
          type:
            - origin
          client:
              clientA:
                clientLimit: 2
                clientRefreshInterval: 78
              clientB:
                clientLimit: 21
                clientRefreshInterval: 45