spring:
  application:
    name: ratelimit-service

redis:
  redisHost: redis://127.0.0.1
  redisPort: 6379
  redisPassword: password
  redisConnectionTimeout: 2000
  redisPoolMaxIdle: 50
  redisPoolMinIdle: 10
  redisPoolMaxWaitMillis: -1
  redisPoolMaxTotal: 200
  redisKeyPrefix: #RL
  checkActionTimeout: 100

intuit:
  ratelimit:
    algorithm: TOKEN_BUCKET
    enabled: true
    service:
      serviceZ:
          limit: 10
          refreshInterval: 60
          refill: 5
          client:
              clientA:
                clientLimit: 2
                clientRefreshInterval: 78
                clientRefill: 1
              clientB:
                clientLimit: 21
                clientRefreshInterval: 100
                clientRefill: 10
      serviceB:
        limit: 20
        refreshInterval: 10
        refill: 5
        client:
          clientA:
            clientLimit: 2
            clientRefreshInterval: 20
            clientRefill: 1
          clientB:
            clientLimit: 10
            clientRefreshInterval: 45
            clientRefill: 4
      serviceC:
        limit: 30
        refreshInterval: 10
        refill: 5
      serviceD:
        limit: 50
        refreshInterval: 100
        refill: 10

